apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - sushi-placement.yaml
#   - sushi-quotas.yaml
#   - sushi-networkpolicies.yaml

generators:
  - policyGenerator.yaml
commonLabels:
  env: prod